-- MySQL Script generated by MySQL Workbench
-- Thu Jul 27 03:44:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tjgimagetag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tjgimagetag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tjgimagetag` DEFAULT CHARACTER SET utf8 ;
USE `tjgimagetag` ;

-- -----------------------------------------------------
-- Table `tjgimagetag`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tjgimagetag`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bucket` VARCHAR(255) NOT NULL,
  `objectkey` VARCHAR(2000) NOT NULL,
  `objectkeysha1` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `objectkeysha1_UNIQUE` (`objectkeysha1` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tjgimagetag`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tjgimagetag`.`labels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `labelname` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `labelname_UNIQUE` (`labelname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tjgimagetag`.`imagelabels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tjgimagetag`.`imagelabels` (
  `imageid` INT NOT NULL,
  `labelid` INT NOT NULL,
  `confidence` FLOAT NOT NULL,
  PRIMARY KEY (`imageid`, `labelid`),
  INDEX `labelid_fk_idx` (`labelid` ASC),
  CONSTRAINT `imageid_fk`
    FOREIGN KEY (`imageid`)
    REFERENCES `tjgimagetag`.`images` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `labelid_fk`
    FOREIGN KEY (`labelid`)
    REFERENCES `tjgimagetag`.`labels` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
